// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCutuTUMlA0BYME46hlNzL5FRqEfoePp3I',
    appId: '1:1037371341426:web:95624f61137fde638aa0eb',
    messagingSenderId: '1037371341426',
    projectId: 'edunet-5e67c',
    authDomain: 'edunet-5e67c.firebaseapp.com',
    storageBucket: 'edunet-5e67c.appspot.com',
    measurementId: 'G-6JCDMZ00EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFHk1CConij4Lh3QchRnTTb8qzWxthLVw',
    appId: '1:1037371341426:android:f0d30fe409dd82ba8aa0eb',
    messagingSenderId: '1037371341426',
    projectId: 'edunet-5e67c',
    storageBucket: 'edunet-5e67c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFSoFW_x1C_ieXm2S3psP1JR0PoTlNdvo',
    appId: '1:1037371341426:ios:9151323b75da10c08aa0eb',
    messagingSenderId: '1037371341426',
    projectId: 'edunet-5e67c',
    storageBucket: 'edunet-5e67c.appspot.com',
    iosBundleId: 'com.example.edunet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFSoFW_x1C_ieXm2S3psP1JR0PoTlNdvo',
    appId: '1:1037371341426:ios:9151323b75da10c08aa0eb',
    messagingSenderId: '1037371341426',
    projectId: 'edunet-5e67c',
    storageBucket: 'edunet-5e67c.appspot.com',
    iosBundleId: 'com.example.edunet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCutuTUMlA0BYME46hlNzL5FRqEfoePp3I',
    appId: '1:1037371341426:web:b34d40968504eb9b8aa0eb',
    messagingSenderId: '1037371341426',
    projectId: 'edunet-5e67c',
    authDomain: 'edunet-5e67c.firebaseapp.com',
    storageBucket: 'edunet-5e67c.appspot.com',
    measurementId: 'G-GGBQKBN32C',
  );
}
